import { phoneList } from './modules/phoneList';
import { burgerMenu } from './modules/burgerMenu';
import { smoothScroll } from './modules/smoothScroll';
import { modals } from './modules/modals';
import { maskPhone } from './modules/maskPhone';
import { sliderTypesOfRepairs } from './modules/sliderTypesOfRepairs';
import { sendForm } from './modules/sendForm';
import { sliderPortfolio } from './modules/slider';
import { sliderPortfolioMobile } from './modules/slider';
import { accordion } from './modules/accordion';
import { getData } from './modules/getData';
import { tooltip } from './modules/tooltip';
import { sliderDocs } from './modules/slider';
import { sliderBenefits } from './modules/slider';

phoneList();
burgerMenu();
smoothScroll();
modals();
maskPhone();
sliderTypesOfRepairs();
sendForm();
sliderPortfolio();
sliderPortfolioMobile();
accordion();
getData();
tooltip();
sliderDocs();
sliderBenefits();