import { phoneList } from './modules/phoneList';
import { burgerMenu } from './modules/burgerMenu';
import { smoothScroll } from './modules/smoothScroll';
import { modals } from './modules/modals';
import { maskPhone } from './modules/maskPhone';
import { sliderTypesOfRepairs } from './modules/sliderTypesOfRepairs';
import { sendForm } from './modules/sendForm';
import { sliderPortfolio } from './modules/sliderPortfolio';
import { sliderPopupPortfolio } from './modules/sliderPopupPortfolio';
import { accordion } from './modules/accordion';
import { getData } from './modules/getData';

phoneList();
burgerMenu();
smoothScroll();
modals();
maskPhone();
sliderTypesOfRepairs();
sendForm();
sliderPortfolio();
sliderPopupPortfolio();
accordion();
getData();